// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBX3vRROV2SJZKdrepzwFGLYqMX3tsM0',
    appId: '1:839911535014:web:2c7e11c0827e58f6681f67',
    messagingSenderId: '839911535014',
    projectId: 'clinic-booking-app-9771d',
    authDomain: 'clinic-booking-app-9771d.firebaseapp.com',
    storageBucket: 'clinic-booking-app-9771d.appspot.com',
    measurementId: 'G-C3716F9TML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54JQB5mkL09fwDNNuI-n8teQnY68cz54',
    appId: '1:839911535014:android:674c2be29819c0af681f67',
    messagingSenderId: '839911535014',
    projectId: 'clinic-booking-app-9771d',
    storageBucket: 'clinic-booking-app-9771d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOydgGvxl4EkTWhu-Yf6XTxQk92WVOvM',
    appId: '1:839911535014:ios:81095bad8b903a29681f67',
    messagingSenderId: '839911535014',
    projectId: 'clinic-booking-app-9771d',
    storageBucket: 'clinic-booking-app-9771d.appspot.com',
    iosBundleId: 'com.example.clinicBookingApp',
  );
}
